### ISSUE TITLE
Add hacktoberfast tag

### ISSUE THREAD

**Issue by eerison** [RikudouSage/DynamoDbCachePsr6Bundle#23]
do you mind to add `hacktoberfest` tag in your repository like here: https://github.com/symfony/symfony

![Screenshot 2022-10-04 at 18 26 59](https://user-images.githubusercontent.com/6358755/193874235-90aecccd-5c74-4652-9004-51b22e9de9d2.png)

maybe I can contribute somehow later with this repo :)

**Comment by RikudouSage** [comment]
What's the point of the tag if I may ask?

**Comment by eerison** [comment]
because just count the PR if your repository has this topic

https://hacktoberfest.com/participation/

> MAINTAINERS
> - Add the “hacktoberfest” topic to your repository to OPT-IN TO HACKTOBERFEST and indicate you’re looking for contributions.

**Comment by RikudouSage** [comment]
Done.
