### ISSUE TITLE
Cannot use adapter as adapter in cache config

### ISSUE THREAD

**Issue by GinoPane** [RikudouSage/DynamoDbCachePsr6Bundle#24]
Hi!
Could you please suggest how to use the services from this package in adapters config?
I have something like this:
![image](https://user-images.githubusercontent.com/3897579/204470168-0f88226a-af4c-43f1-8f21-fefca6b66458.png)

```Rikudou\\DynamoDbCacheBundle\\Cache\\DynamoDbCacheAdapter::__construct(): Argument #1 ($cache) must be of type Rikudou\\DynamoDbCache\\DynamoDbCache, string given, called in /application/var/cache/qa/Container2ANkKkQ/getDealerHierarchyServiceService.php on line 23```

And whenever I try to do else the adapter is not injectable. I got either "service does not exist" or "cannot inject argument as service is not yet configured" etc

**Comment by GinoPane** [comment]
If trying to use it as a service I get: 
![image](https://user-images.githubusercontent.com/3897579/204475141-7af057dd-696a-4fb0-89e5-c5e10cd94cb4.png)

**Comment by RikudouSage** [comment]
I know about the problem of using it as an adapter directly, sadly never found a solution for that. Symfony for some reason injects a string as the first argument instead of the configured one.

Where are you trying to import the service directly? That should AFAIK work.

**Comment by GinoPane** [comment]
Yes, I switched to using this cache as a standalone service.
Thanks

**Comment by RikudouSage** [comment]
You can also make the `CacheItemPoolInterface` (or `AdapterInterface`) an alias to the service by default if you want to avoid a vendor lock-in.
