### ISSUE TITLE
Prefix/Namespace

### ISSUE THREAD

**Issue by chekalsky** [RikudouSage/DynamoDbCachePsr6Bundle#6]
What is the right way to have prefix/namespace for cache keys? e.g. having separate caches for different versions of code or different environments?

**Comment by RikudouSage** [comment]
There's none so far, you need to create different table for different cache or handle it in your app (e.g. write some cache service that will automatically prefix the key with your choosen string).

I can't think of a good way to support prefixes on the bundle level, do you have any ideas?
